2019-05-16 10:26:59.172 +03:00 [Fatal] Unable to start Kestrel.
System.IO.IOException: Failed to bind to address https://127.0.0.1:5001: address already in use. ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use ---> System.Net.Sockets.SocketException: Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
2019-05-16 10:26:59.236 +03:00 [Fatal] Host terminated unexpectedly
System.IO.IOException: Failed to bind to address https://127.0.0.1:5001: address already in use. ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use ---> System.Net.Sockets.SocketException: Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass21_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Dwapi.Hts.Program.Main(String[] args) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts/Program.cs:line 30
2019-05-16 10:57:15.532 +03:00 [Error] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Unable to resolve service for type 'Dwapi.Hts.Core.Interfaces.Repository.IHtsClientLinkageRepository' while attempting to activate 'Dwapi.Hts.Core.Service.HtsService'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2019-05-16 11:37:56.917 +03:00 [Error] Facility Id missing 10001
Dwapi.Hts.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10001
   at Dwapi.Hts.Core.Service.HtsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/Service/HtsService.cs:line 154
   at Dwapi.Hts.Core.Service.HtsService.Process(IEnumerable`1 clients) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/Service/HtsService.cs:line 45
2019-05-16 11:38:02.593 +03:00 [Error] Facility Id missing 10001
Dwapi.Hts.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10001
   at Dwapi.Hts.Core.Service.HtsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/Service/HtsService.cs:line 154
   at Dwapi.Hts.Core.Service.HtsService.Process(IEnumerable`1 clients) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/Service/HtsService.cs:line 45
2019-05-16 11:38:02.696 +03:00 [Error] Facility Id missing 10001
Dwapi.Hts.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10001
   at Dwapi.Hts.Core.Service.HtsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/Service/HtsService.cs:line 154
   at Dwapi.Hts.Core.Service.HtsService.Process(IEnumerable`1 clients) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/Service/HtsService.cs:line 45
2019-05-16 11:38:02.798 +03:00 [Error] Facility Id missing 10001
Dwapi.Hts.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10001
   at Dwapi.Hts.Core.Service.HtsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/Service/HtsService.cs:line 154
   at Dwapi.Hts.Core.Service.HtsService.Process(IEnumerable`1 clients) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/Service/HtsService.cs:line 45
2019-05-16 11:38:02.899 +03:00 [Error] Facility Id missing 10001
Dwapi.Hts.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10001
   at Dwapi.Hts.Core.Service.HtsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/Service/HtsService.cs:line 154
   at Dwapi.Hts.Core.Service.HtsService.Process(IEnumerable`1 clients) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/Service/HtsService.cs:line 45
2019-05-16 11:38:04.409 +03:00 [Error] Facility Id missing 10002
Dwapi.Hts.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10002
   at Dwapi.Hts.Core.Service.HtsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/Service/HtsService.cs:line 154
   at Dwapi.Hts.Core.Service.HtsService.Process(IEnumerable`1 clients) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/Service/HtsService.cs:line 45
2019-05-16 11:38:04.510 +03:00 [Error] Facility Id missing 10002
Dwapi.Hts.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10002
   at Dwapi.Hts.Core.Service.HtsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/Service/HtsService.cs:line 154
   at Dwapi.Hts.Core.Service.HtsService.Process(IEnumerable`1 clients) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/Service/HtsService.cs:line 45
2019-05-16 11:38:04.609 +03:00 [Error] Facility Id missing 10002
Dwapi.Hts.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10002
   at Dwapi.Hts.Core.Service.HtsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/Service/HtsService.cs:line 154
   at Dwapi.Hts.Core.Service.HtsService.Process(IEnumerable`1 clients) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/Service/HtsService.cs:line 45
2019-05-16 11:38:04.741 +03:00 [Error] Facility Id missing 10002
Dwapi.Hts.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10002
   at Dwapi.Hts.Core.Service.HtsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/Service/HtsService.cs:line 154
   at Dwapi.Hts.Core.Service.HtsService.Process(IEnumerable`1 clients) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/Service/HtsService.cs:line 45
2019-05-16 11:38:04.880 +03:00 [Error] Facility Id missing 10002
Dwapi.Hts.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10002
   at Dwapi.Hts.Core.Service.HtsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/Service/HtsService.cs:line 154
   at Dwapi.Hts.Core.Service.HtsService.Process(IEnumerable`1 clients) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/Service/HtsService.cs:line 45
2019-05-16 12:49:19.447 +03:00 [Error] Execution DelayedJobScheduler is in the Failed state now due to an exception, execution will be retried no more than in 00:00:09
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "HTSCentralDev" requested by the login. The login failed.
Login failed for user 'sa'.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerConnection.AcquireLock(String resource, TimeSpan timeout)
   at Hangfire.SqlServer.SqlServerConnection.AcquireDistributedLock(String resource, TimeSpan timeout)
   at Hangfire.Server.DelayedJobScheduler.UseConnectionDistributedLock[T](JobStorage storage, Func`2 action)
   at Hangfire.Server.DelayedJobScheduler.Execute(BackgroundProcessContext context)
   at Hangfire.Server.BackgroundProcessDispatcherBuilder.ExecuteProcess(Guid executionId, Object state)
   at Hangfire.Processing.BackgroundExecution.Run(Action`2 callback, Object state)
ClientConnectionId:173da88e-f872-4387-845b-eec609c51d60
Error Number:4060,State:1,Class:11
2019-05-16 12:49:19.447 +03:00 [Error] Execution RecurringJobScheduler is in the Failed state now due to an exception, execution will be retried no more than in 00:00:09
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "HTSCentralDev" requested by the login. The login failed.
Login failed for user 'sa'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerConnection.AcquireLock(String resource, TimeSpan timeout)
   at Hangfire.SqlServer.SqlServerConnection.AcquireDistributedLock(String resource, TimeSpan timeout)
   at Hangfire.Server.RecurringJobScheduler.UseConnectionDistributedLock(JobStorage storage, Func`2 action)
   at Hangfire.Server.RecurringJobScheduler.Execute(BackgroundProcessContext context)
   at Hangfire.Server.BackgroundProcessDispatcherBuilder.ExecuteProcess(Guid executionId, Object state)
   at Hangfire.Processing.BackgroundExecution.Run(Action`2 callback, Object state)
ClientConnectionId:173da88e-f872-4387-845b-eec609c51d60
Error Number:4060,State:1,Class:11
2019-05-16 12:49:19.447 +03:00 [Error] Execution Worker is in the Failed state now due to an exception, execution will be retried no more than in 00:05:00
System.Data.SqlClient.SqlException (0x80131904): Cannot open database "HTSCentralDev" requested by the login. The login failed.
Login failed for user 'sa'.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Hangfire.SqlServer.SqlServerStorage.CreateAndOpenConnection()
   at Hangfire.SqlServer.SqlServerJobQueue.DequeueUsingTransaction(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerJobQueue.Dequeue(String[] queues, CancellationToken cancellationToken)
   at Hangfire.SqlServer.SqlServerConnection.FetchNextJob(String[] queues, CancellationToken cancellationToken)
   at Hangfire.Server.Worker.Execute(BackgroundProcessContext context)
   at Hangfire.Server.BackgroundProcessDispatcherBuilder.ExecuteProcess(Guid executionId, Object state)
   at Hangfire.Processing.BackgroundExecution.Run(Action`2 callback, Object state)
ClientConnectionId:173da88e-f872-4387-845b-eec609c51d60
Error Number:4060,State:1,Class:11
2019-05-16 13:06:58.046 +03:00 [Error] manifest error
Dwapi.Hts.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 13840
   at Dwapi.Hts.Core.CommandHandler.ValidateFacilityHandler.Handle(ValidateFacility request, CancellationToken cancellationToken) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/CommandHandler/ValidateFacilityHandler.cs:line 27
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at Dwapi.Hts.Core.CommandHandler.EnrollFacilityHandler.Handle(EnrollFacility request, CancellationToken cancellationToken) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/CommandHandler/EnrollFacilityHandler.cs:line 26
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at Dwapi.Hts.Core.CommandHandler.SaveManifestHandler.Handle(SaveManifest request, CancellationToken cancellationToken) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts.Core/CommandHandler/SaveManifestHandler.cs:line 23
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at Dwapi.Hts.Controllers.HtsController.ProcessManifest(SaveManifest manifest) in /Users/koskedk/Projects/hmis/dwh/dwapi/hts/src/Dwapi.Hts/Controllers/HtsController.cs:line 58
